$schema: http://json-schema.org/draft-07/schema#
type: object
properties:
  blank_issues_enabled:
    type: boolean
  contact_links:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
          format: uri
        about:
          type: string
      required:
      - name
      - url
      - about
      additionalProperties: false
required:
- blank_issues_enabled
additionalProperties: false
